use diffy;
use std::env;
use std::fmt::{Debug, Display};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use tracing::{debug, error, info, trace};
use walkdir::WalkDir;

pub enum FormatCodeError {
    // IO Error when running code formatter
    Io(std::io::Error),
    /// An error occured that prevents code formatting. For example, a parse error.
    CodeNotFormatted(Vec<u8>),
}

impl From<std::io::Error> for FormatCodeError {
    fn from(error: std::io::Error) -> Self {
        Self::Io(error)
    }
}

impl std::fmt::Debug for FormatCodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(e) => std::fmt::Debug::fmt(e, f),
            Self::CodeNotFormatted(e) => {
                let data = String::from_utf8_lossy(e);
                f.write_str(&data)
            }
        }
    }
}

pub enum CreateDiffError {
    /// Couldn't create a diff because the rustfmt binary compiled from the `main` branch
    /// failed to format the input.
    MainRustfmtFailed(FormatCodeError),
    /// Couldn't create a diff because the rustfmt binary compiled from the `feature` branch
    /// failed to format the input.
    FeatureRustfmtFailed(FormatCodeError),
    /// Couldn't create a diff because both rustfmt binaries failed to format the input
    BothRustfmtFailed {
        src: FormatCodeError,
        feature: FormatCodeError,
    },
}

#[derive(Debug)]
pub enum CheckDiffError {
    /// Git related errors
    FailedGit(GitError),
    /// Error for generic commands
    FailedCommand(&'static str),
    /// Error for building rustfmt from source
    FailedSourceBuild(&'static str),
    /// Error when obtaining binary version
    FailedBinaryVersioning(PathBuf),
    /// Error when obtaining cargo version
    FailedCargoVersion(&'static str),
    IO(std::io::Error),
}

impl From<io::Error> for CheckDiffError {
    fn from(error: io::Error) -> Self {
        CheckDiffError::IO(error)
    }
}

impl From<GitError> for CheckDiffError {
    fn from(error: GitError) -> Self {
        CheckDiffError::FailedGit(error)
    }
}

#[derive(Debug)]
pub enum GitError {
    FailedClone { stdout: Vec<u8>, stderr: Vec<u8> },
    FailedRemoteAdd { stdout: Vec<u8>, stderr: Vec<u8> },
    FailedFetch { stdout: Vec<u8>, stderr: Vec<u8> },
    FailedSwitch { stdout: Vec<u8>, stderr: Vec<u8> },
    IO(std::io::Error),
}

impl From<io::Error> for GitError {
    fn from(error: io::Error) -> Self {
        GitError::IO(error)
    }
}

pub struct Diff {
    src_format: String,
    feature_format: String,
}

impl Display for Diff {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let patch = diffy::create_patch(self.src_format.as_str(), self.feature_format.as_str());
        write!(f, "{}", patch)
    }
}

impl Diff {
    pub fn is_empty(&self) -> bool {
        let patch = diffy::create_patch(self.src_format.as_str(), self.feature_format.as_str());
        patch.hunks().is_empty()
    }
}

pub struct CheckDiffRunners<F, S> {
    feature_runner: F,
    src_runner: S,
}

pub trait CodeFormatter {
    fn format_code<T: AsRef<str>>(
        &self,
        code: &str,
        config: Option<&[T]>,
    ) -> Result<String, FormatCodeError>;
}

pub struct RustfmtRunner {
    dynamic_library_path: String,
    binary_path: PathBuf,
}

impl<F, S> CheckDiffRunners<F, S> {
    pub fn new(feature_runner: F, src_runner: S) -> Self {
        Self {
            feature_runner,
            src_runner,
        }
    }
}

impl<F, S> CheckDiffRunners<F, S>
where
    F: CodeFormatter,
    S: CodeFormatter,
{
    /// Creates a diff generated by running the source and feature binaries on the same file path
    pub fn create_diff<T: AsRef<str>>(
        &self,
        path: &Path,
        additional_configs: Option<&[T]>,
    ) -> Result<Diff, CreateDiffError> {
        let code = std::fs::read_to_string(path).expect("we can read the file");
        let src_format = self.src_runner.format_code(&code, additional_configs);
        let feature_format = self.feature_runner.format_code(&code, additional_configs);

        match (src_format, feature_format) {
            (Ok(s), Ok(f)) => Ok(Diff {
                src_format: s,
                feature_format: f,
            }),
            (Err(error), Ok(_)) => {
                // main formatting failed.
                Err(CreateDiffError::MainRustfmtFailed(error))
            }
            (Ok(_), Err(error)) => {
                // feature formatting failed
                Err(CreateDiffError::FeatureRustfmtFailed(error))
            }
            (Err(src_error), Err(feature_error)) => {
                // Both main formatting and feature formatting failed
                Err(CreateDiffError::BothRustfmtFailed {
                    src: src_error,
                    feature: feature_error,
                })
            }
        }
    }
}

impl RustfmtRunner {
    fn get_binary_version(&self) -> Result<String, CheckDiffError> {
        let Ok(command) = Command::new(&self.binary_path)
            .env(
                dynamic_library_path_env_var_name(),
                &self.dynamic_library_path,
            )
            .args(["--version"])
            .output()
        else {
            return Err(CheckDiffError::FailedBinaryVersioning(
                self.binary_path.clone(),
            ));
        };

        Ok(buffer_into_utf8_lossy(command.stdout))
    }
}

/// Convert a buffer of u8 into a String.
fn buffer_into_utf8_lossy(buffer: Vec<u8>) -> String {
    let mut s = match String::from_utf8(buffer) {
        Ok(s) => s,
        Err(e) => String::from_utf8_lossy(e.as_bytes()).to_string(),
    };
    s.truncate(s.trim_end().len());
    s
}

/// Returns the name of the environment variable used to search for dynamic libraries.
/// This is the same logic that cargo uses when setting these environment variables
fn dynamic_library_path_env_var_name() -> &'static str {
    if cfg!(windows) {
        "PATH"
    } else if cfg!(target_os = "macos") {
        "DYLD_FALLBACK_LIBRARY_PATH"
    } else if cfg!(target_os = "aix") {
        "LIBPATH"
    } else {
        "LD_LIBRARY_PATH"
    }
}

impl CodeFormatter for RustfmtRunner {
    //  Run rusfmt to see if a diff is produced. Runs on the code specified
    //
    // Parameters:
    // code: Code to run the binary on
    // config: Any additional configuration options to pass to rustfmt
    //
    fn format_code<T: AsRef<str>>(
        &self,
        code: &str,
        config: Option<&[T]>,
    ) -> Result<String, FormatCodeError> {
        let config = create_config_arg(config);
        let mut command = Command::new(&self.binary_path)
            .env(
                dynamic_library_path_env_var_name(),
                &self.dynamic_library_path,
            )
            .args([
                "--unstable-features",
                "--skip-children",
                "--emit=stdout",
                config.as_str(),
            ])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()?;

        command.stdin.as_mut().unwrap().write_all(code.as_bytes())?;
        let output = command.wait_with_output()?;
        let formatted_code = buffer_into_utf8_lossy(output.stdout);

        match output.status.code() {
            Some(0) => Ok(formatted_code),
            Some(_) | None => {
                if !formatted_code.is_empty() {
                    Ok(formatted_code)
                } else {
                    Err(FormatCodeError::CodeNotFormatted(output.stderr))
                }
            }
        }
    }
}

/// Creates a configuration in the following form:
/// <config_name>=<config_val>, <config_name>=<config_val>, ...
fn create_config_arg<T: AsRef<str>>(config: Option<&[T]>) -> String {
    let config_arg: String = match config {
        Some(configs) => {
            let mut result = String::new();
            for arg in configs.iter() {
                result.push(',');
                result.push_str(arg.as_ref());
            }
            result
        }
        None => String::new(),
    };
    let config = format!(
        "--config=error_on_line_overflow=false,error_on_unformatted=false{}",
        config_arg.as_str()
    );
    config
}
/// Clone a git repository
///
/// Parameters:
/// url: git clone url
/// dest: directory where the repo should be cloned
pub fn clone_git_repo(url: &str, dest: &Path) -> Result<(), GitError> {
    let git_cmd = Command::new("git")
        .env("GIT_TERMINAL_PROMPT", "0")
        .args([
            "clone",
            "--quiet",
            url,
            "--depth",
            "1",
            dest.to_str().unwrap(),
        ])
        .output()?;

    // if the git command does not return successfully,
    // any command on the repo will fail. So fail fast.
    if !git_cmd.status.success() {
        let error = GitError::FailedClone {
            stdout: git_cmd.stdout,
            stderr: git_cmd.stderr,
        };
        return Err(error);
    }

    info!("Successfully cloned repository {url} to {}", dest.display());
    Ok(())
}

pub fn git_remote_add(url: &str) -> Result<(), GitError> {
    let git_cmd = Command::new("git")
        .args(["remote", "add", "feature", url])
        .output()?;

    // if the git command does not return successfully,
    // any command on the repo will fail. So fail fast.
    if !git_cmd.status.success() {
        let error = GitError::FailedRemoteAdd {
            stdout: git_cmd.stdout,
            stderr: git_cmd.stderr,
        };
        return Err(error);
    }

    info!("Successfully added remote: {url}");
    return Ok(());
}

pub fn git_fetch(branch_name: &str) -> Result<(), GitError> {
    let git_cmd = Command::new("git")
        .args(["fetch", "feature", branch_name])
        .output()?;

    // if the git command does not return successfully,
    // any command on the repo will fail. So fail fast.
    if !git_cmd.status.success() {
        let error = GitError::FailedFetch {
            stdout: git_cmd.stdout,
            stderr: git_cmd.stderr,
        };
        return Err(error);
    }

    info!("Successfully fetched: {branch_name}");
    return Ok(());
}

pub fn git_switch(git_ref: &str, should_detach: bool) -> Result<(), GitError> {
    let detach_arg = if should_detach { "--detach" } else { "" };
    let args = ["switch", git_ref, detach_arg];
    let output = Command::new("git")
        .args(args.iter().filter(|arg| !arg.is_empty()))
        .output()?;
    if !output.status.success() {
        tracing::error!("Git switch failed: {output:?}");
        let error = GitError::FailedSwitch {
            stdout: output.stdout,
            stderr: output.stderr,
        };
        return Err(error);
    }
    info!("Successfully switched to {git_ref}");
    return Ok(());
}

pub fn change_directory_to_path(dest: &Path) -> io::Result<()> {
    let dest_path = Path::new(&dest);
    env::set_current_dir(&dest_path)?;
    info!(
        "Setting current directory to: {}",
        env::current_dir().unwrap().display()
    );
    return Ok(());
}

pub fn get_dynamic_library_path(dir: &Path) -> Result<String, CheckDiffError> {
    let Ok(command) = Command::new("rustc")
        .current_dir(dir)
        .args(["--print", "sysroot"])
        .output()
    else {
        return Err(CheckDiffError::FailedCommand("Error getting sysroot"));
    };
    let mut sysroot = buffer_into_utf8_lossy(command.stdout);
    sysroot.push_str("/lib");
    Ok(sysroot)
}

pub fn get_cargo_version() -> Result<String, CheckDiffError> {
    let Ok(command) = Command::new("cargo").args(["--version"]).output() else {
        return Err(CheckDiffError::FailedCargoVersion(
            "Failed to obtain cargo version",
        ));
    };

    Ok(buffer_into_utf8_lossy(command.stdout))
}

/// Obtains the ld_lib path and then builds rustfmt from source
/// If that operation succeeds, the source is then copied to the output path specified
pub fn build_rustfmt_from_src(
    binary_path: PathBuf,
    dir: &Path,
) -> Result<RustfmtRunner, CheckDiffError> {
    // Because we're building standalone binaries we need to set the dynamic library path
    // so each rustfmt binary can find it's runtime dependencies.
    let dynamic_library_path = get_dynamic_library_path(dir)?;

    info!("Building rustfmt from source");
    let Ok(_) = Command::new("cargo")
        .current_dir(dir)
        .args(["build", "-q", "--release", "--bin", "rustfmt"])
        .output()
    else {
        return Err(CheckDiffError::FailedSourceBuild(
            "Error building rustfmt from source",
        ));
    };

    std::fs::copy(dir.join("target/release/rustfmt"), &binary_path)?;

    Ok(RustfmtRunner {
        dynamic_library_path,
        binary_path,
    })
}

// Compiles and produces two rustfmt binaries.
// One for the current main branch, and another for the feature branch
// Parameters:
// dest: Directory where rustfmt will be cloned
pub fn compile_rustfmt(
    dest: &Path,
    remote_repo_url: String,
    feature_branch: String,
    commit_hash: Option<String>,
) -> Result<CheckDiffRunners<RustfmtRunner, RustfmtRunner>, CheckDiffError> {
    const RUSTFMT_REPO: &str = "https://github.com/rust-lang/rustfmt.git";

    clone_git_repo(RUSTFMT_REPO, dest)?;
    change_directory_to_path(dest)?;
    git_remote_add(remote_repo_url.as_str())?;
    git_fetch(feature_branch.as_str())?;

    let cargo_version = get_cargo_version()?;
    info!("Compiling with {}", cargo_version);
    let src_runner = build_rustfmt_from_src(dest.join("src_rustfmt"), dest)?;
    let should_detach = commit_hash.is_some();
    git_switch(
        commit_hash.as_ref().unwrap_or(&feature_branch),
        should_detach,
    )?;

    let feature_runner = build_rustfmt_from_src(dest.join("feature_rustfmt"), dest)?;
    info!("RUSFMT_BIN {}", src_runner.get_binary_version()?);
    let dynamic_library_path_env_var = dynamic_library_path_env_var_name();
    info!(
        "Runtime dependencies for (main) rustfmt -- {}: {}",
        dynamic_library_path_env_var, src_runner.dynamic_library_path
    );
    info!("FEATURE_BIN {}", feature_runner.get_binary_version()?);
    info!(
        "Runtime dependencies for ({}) rustfmt -- {}: {}",
        feature_branch, dynamic_library_path_env_var, feature_runner.dynamic_library_path
    );

    return Ok(CheckDiffRunners {
        src_runner,
        feature_runner,
    });
}

/// Searches for rust files in the particular path and returns an iterator to them.
pub fn search_for_rs_files(repo: &Path) -> impl Iterator<Item = PathBuf> {
    return WalkDir::new(repo).into_iter().filter_map(|e| match e.ok() {
        Some(entry) => {
            let path = entry.path();
            if path.is_file() && path.extension().map_or(false, |ext| ext == "rs") {
                return Some(entry.into_path());
            }
            return None;
        }
        None => None,
    });
}

/// Calculates the number of errors when running the compiled binary and the feature binary on the
/// repo specified with the specific configs.
pub fn check_diff<T: AsRef<str>>(
    config: Option<&[T]>,
    runners: &CheckDiffRunners<impl CodeFormatter, impl CodeFormatter>,
    repo: &Path,
    repo_url: &str,
) -> i32 {
    let mut errors = 0;
    let iter = search_for_rs_files(repo);
    for file in iter {
        let relative_path = file.strip_prefix(repo).unwrap_or(&file);
        let repo_name = get_repo_name(repo_url);

        trace!(
            "Formatting '{0}' file {0}/{1}",
            repo_name,
            relative_path.display()
        );

        match runners.create_diff(file.as_path(), config) {
            Ok(diff) => {
                if !diff.is_empty() {
                    error!(
                        "Diff found in '{0}' when formatting {0}/{1}\n{2}",
                        repo_name,
                        relative_path.display(),
                        diff,
                    );
                    errors += 1;
                } else {
                    trace!(
                        "No diff found in '{0}' when formatting {0}/{1}",
                        repo_name,
                        relative_path.display(),
                    )
                }
            }
            Err(CreateDiffError::MainRustfmtFailed(e)) => {
                debug!(
                    "`main` rustfmt failed to format {}/{}\n{:?}",
                    repo_name,
                    relative_path.display(),
                    e,
                );
                continue;
            }
            Err(CreateDiffError::FeatureRustfmtFailed(e)) => {
                debug!(
                    "`feature` rustfmt failed to format {}/{}\n{:?}",
                    repo_name,
                    relative_path.display(),
                    e,
                );
                continue;
            }
            Err(CreateDiffError::BothRustfmtFailed { src, feature }) => {
                debug!(
                    "Both rustfmt binaries failed to format {}/{}\n{:?}\n{:?}",
                    repo_name,
                    relative_path.display(),
                    src,
                    feature,
                );
                continue;
            }
        }
    }

    errors
}

/// parse out the repository name from a GitHub Repository name.
pub fn get_repo_name(git_url: &str) -> &str {
    let strip_git_prefix = git_url.strip_suffix(".git").unwrap_or(git_url);
    let (_, repo_name) = strip_git_prefix
        .rsplit_once('/')
        .unwrap_or(("", strip_git_prefix));
    repo_name
}
