name: Diff Check
on:
  workflow_dispatch:
    inputs:
      clone_url:
        description: 'Git url of a rustfmt fork to compare against the latest rustfmt'
        required: true
      branch_name:
        description: 'Name of the feature branch on the forked repo'
        required: true
      edition:
        description: 'Which rust `edition` to use when parsing code'
        required: true
        type: choice
        options:
          - '2015'
          - '2018'
          - '2021'
          - '2024'
        default: '2015'
      style_edition:
        description: 'Which rustfmt `style_edition` to use when formatting'
        required: true
        type: choice
        options:
          - '2021' # 2015, 2018, and 2021 are all the same for `style_edition`
          - '2024'
        default: '2021'
      commit_hash:
        description: 'Optional commit hash from the feature branch'
        required: false
      rustfmt_configs:
        description: 'Optional comma separated list of rustfmt config options to pass when running the feature branch'
        required: false

jobs:
  diff_check:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none
        rustup target add x86_64-unknown-linux-gnu

    - name: check diff
      run: bash ${GITHUB_WORKSPACE}/ci/check_diff.sh ${{ github.event.inputs.clone_url }} ${{ github.event.inputs.branch_name }} ${{ github.event.inputs.edition }} ${{ github.event.inputs.style_edition }} ${{ github.event.inputs.commit_hash || github.event.inputs.branch_name }} ${{ github.event.inputs.rustfmt_configs }}
